
markdown: kramdown

redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

kramdown:
  input: GFM

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate

author:
  name: Jason Turner

feed:
  path: node/feed.xml


paginate: 10
